# -----------------------------------------------------------------------------
# GitHub Actions CI/CD Pipeline for Building and Pushing Docker Images to GHCR
# -----------------------------------------------------------------------------
# This pipeline automates the process of building and pushing Docker images to
# GitHub Container Registry (GHCR) whenever code is pushed to the 'dev' branch.
# 
# Pipeline Overview:
# 1. **Build Process**: 
#    - The pipeline is triggered on a push to the 'main' branch.
#    - It builds Docker images from the source,using Dockerfiles located within those directories.    
#    - A unique image tag is created based on the commit's short SHA (`$GITHUB_SHA::8`).
#    - Docker Buildx is used to build the image, and the image is tagged with the
#      commit SHA and pushed to GitHub Container Registry (GHCR).
# 
# 2. **GHCR (GitHub Container Registry)**:
#    - The images are pushed to GHCR in the format:
#      `ghcr.io/<OWNER>/<REPO>/<SERVICE_NAME>:<IMAGE_TAG>`.
#    - After the image is successfully pushed, it can be referenced in Helm charts
#      or Kubernetes deployments using this exact registry and tag.
# 
# 3. **Helm Chart Integration**:
#    - The image can be referenced in Kubernetes deployments via Helm charts.
#    - The Helm chart pulls the image from GHCR using the repository, service name,
#      and image tag. The image tag (commit SHA) ensures the deployment uses the
#      exact version of the image that was built in the CI pipeline.
name: Build and push Docker images

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  # you can change this to a short SHA in the run steps if you want
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} \
            -u "${{ github.actor }}" --password-stdin
      - name: Build & push tsn-service image
        run: |
          SERVICE_NAME="tsn-service"
        
          IMAGE_TAG=${GITHUB_SHA::8}
      
          # Lowercase the GitHub repository (e.g. OpenCNC_tsn-service -> opencnc_tsn-service)
          REPO_LC=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
      
          IMAGE="ghcr.io/${REPO_LC}/${SERVICE_NAME}:${IMAGE_TAG}"
      
          echo "Building Docker image $IMAGE from $SERVICE_DIR"
          docker build -t "$IMAGE" . 
      
          echo "Pushing image $IMAGE"
          docker push "$IMAGE"
